name: flutter_interview_questions
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/questions/index.json
    - assets/questions/en/
    - assets/questions/zh/

  fonts:
    - family: Courier
      fonts:
        - asset: assets/fonts/courier.ttf