name: Flutter Web Deploy
on:
  push:
    branches:
      - release
  workflow_dispatch:
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.5'
          channel: 'stable'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release --base-href="/flutter_interview_questions/"
      - run: |
          cd build/web
          git init
          git config --global user.email h65wang@uwaterloo.ca
          git config --global user.name h65wang
          git config --global init.defaultBranch release
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/h65wang/flutter_interview_questions.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
